backend:
  name: github
  repo: andriimuzhytskyi-art/andriimuzhytskyi-art.github.io
  branch: main
  auth_type: implicit
  client_id: Ov23li6fSQSiDKjR34X2

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Новости"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст новости", name: "body", widget: "markdown" }
